### ISSUE TITLE
Regarding hierarchical multi-label classification

### ISSUE THREAD

**Issue by spartian** [davidwarshaw/hmc#11]
Hello,

I am a bit confused with your description. It says that you implemented Hierarchical multi classifier. Is it Hierarchical multi-label classifier or not?

**Comment by ClaudeCoulombe** [comment]
Greetings Spartian, It seems to me that hmc is rather hierarchical single-label multi-class classification. Do you agree?

**Comment by davidwarshaw** [comment]
Yes, this is a single label, multi-classifier.
