### ISSUE TITLE
Hiearchy

### ISSUE THREAD

**Issue by arita37** [davidwarshaw/hmc#5]
Dear David,

I found your implementation of HMC interesting.
Just wondering if there is a way to adapt for hiearchy input features.
Instead of choosing randomly the features, we can choose the
input  features based on a given hiearchy.

What would you think ?

Thanks

**Comment by davidwarshaw** [comment]
I'm not sure I know what you mean.

The purpose of hierarchical classification is to bring information about the relationships between classes (where it exists) into the classification decision. For example, if you know that _all_ _B_ are _A_, but that _no_ _C_ are _A_, then the probability for labels _B_ and _C_ should be conditional on the probability for label _A_.

**Comment by arita37** [comment]
Hi,

Sure, you're right.
One another point is the hiearchy in the output classes, as you mentionned
    Fruit --> Orange
    Fruit --> Banana

But, there is also hiearchy in the input features of the classifier 
(input data have hiearchy).
   If my inputs columns are :
          f1                   f2                                f3
          fruit             orange                     5kg
          meat            beef                          1kg

When building the tree, suppose we have 1 millions input features 
(instead of 3...),
we know given the nature of the data than
      f1 >>   (f2 or f3)

than feature f1 should be higher level in the decision tree.

Instead of having random selection of features at each node, it's better 
to have hiearchy selection.

What would you think ?

Thanks
Brook

**Comment by davidwarshaw** [comment]
You will not have good results fitting a decision tree with millions of features regardless of the splitting strategy. You should perform some kind of dimensionality reduction before hand.

**Comment by arita37** [comment]
Hi,

Yes, that's why i would to introduce hiearchy in the input features,
since it would reduce the dimensionality.

Instead of searching into  the millions of features at each node,
we can only select into a sub-set at each node (different subset at each node).

Hiearchy is provided by the user like the example of meat and banana.

What would you think ?

Kind regards
Kevin
